/*
 * Application: TCGA2BED
 * Version: 1.0
 * Author: Fabio Cumbo
 * Organization: Institute for Systems Analysis and Computer Science "Antonio Ruberti" - National Research Council of Italy
 *
 */
package tcga2bed.util;

import java.util.HashMap;

public class HTTPExpInfo {

    private static HashMap<String, HashMap<String, String>> diseaseInfo = new HashMap<>();

    public static HashMap<String, HashMap<String, String>> getDiseaseInfo() {
        return diseaseInfo;
    }

    public static void initDiseaseInfo() {
        diseaseInfo = new HashMap<>();

        HashMap<String, String> info = new HashMap<>();
        info.put("disease", "Adrenocortical carcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_ACC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_ACC.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_ACC.IlluminaHiSeq_miRNASeq.Level_3");
        info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_ACC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_ACC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_ACC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("acc", info);

        info = new HashMap<>();
        info.put("disease", "Bladder Urothelial Carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_BLCA.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_BLCA.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_BLCA.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_BLCA.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_BLCA.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_BLCA.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_BLCA.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("blca", info);

        info = new HashMap<>();
        info.put("disease", "Breast Invasive carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_BRCA.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_BRCA.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "genome.wustl.edu_BRCA.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_BRCA.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_BRCA.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_BRCA.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_BRCA.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_BRCA.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("brca", info);

        info = new HashMap<>();
        info.put("disease", "Cervical squamous cell carcinoma and endocervical adenocarcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_CESC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "genome.wustl.edu_CESC.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_CESC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_CESC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_CESC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_CESC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("cesc", info);

        info = new HashMap<>();
        info.put("disease", "Cholangiocarcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_CHOL.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_CHOL.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_CHOL.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_CHOL.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_CHOL.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_CHOL.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("chol", info);

        info = new HashMap<>();
        info.put("disease", "Colon adenocarcinoma");
        info.put("rnaseq_platform", "Illumina_GA2");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_COAD.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_COAD.IlluminaGA_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_COAD.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_COAD.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_COAD.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_COAD.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_COAD.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_COAD.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("coad", info);

        info = new HashMap<>();
        info.put("disease", "Lymphoid Neoplasm Diffuse Large B-cell Lymphoma");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_DLBC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_DLBC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_DLBC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_DLBC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_DLBC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("dlbc", info);

        info = new HashMap<>();
        info.put("disease", "Esophageal carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseq_data_dir_prefix", "bcgsc.ca_ESCA.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_ESCA.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_ESCA.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_ESCA.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_ESCA.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_ESCA.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("esca", info);

        info = new HashMap<>();
        info.put("disease", "Glioblastoma multiforme");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_GBM.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_GBM.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_GBM.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_GBM.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_GBM.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_GBM.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_GBM.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("gbm", info);

        info = new HashMap<>();
        info.put("disease", "Head and Neck squamous cell carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_HNSC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_HNSC.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_HNSC.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_HNSC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_HNSC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_HNSC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_HNSC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("hnsc", info);

        info = new HashMap<>();
        info.put("disease", "Kidney Chromophobe");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_KICH.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_KICH.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_KICH.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_KICH.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_KICH.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_KICH.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("kich", info);

        info = new HashMap<>();
        info.put("disease", "Kidney renal clear cell carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_KIRC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_KIRC.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_KIRC.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_KIRC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_KIRC.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_KIRC.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_KIRC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_KIRC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("kirc", info);

        info = new HashMap<>();
        info.put("disease", "Kidney renal papillary cell carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_KIRP.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_KIRP.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_KIRP.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_KIRP.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_KIRP.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_KIRP.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_KIRP.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_KIRP.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("kirp", info);

        info = new HashMap<>();
        info.put("disease", "Acute Myeloid Leukemia");
        info.put("rnaseq_platform", "Illumina_GA2");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_GA2");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_LAML.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "bcgsc.ca_LAML.IlluminaGA_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "genome.wustl.edu_LAML.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_LAML.IlluminaGA_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_LAML.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_LAML.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_LAML.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_LAML.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("laml", info);

        info = new HashMap<>();
        info.put("disease", "Brain Lower Grade Glioma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_LGG.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_LGG.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_LGG.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_LGG.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_LGG.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_LGG.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("lgg", info);

        info = new HashMap<>();
        info.put("disease", "Liver hepatocellular carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_LIHC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_LIHC.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_LIHC.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_LIHC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_LIHC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_LIHC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_LIHC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("lihc", info);

        info = new HashMap<>();
        info.put("disease", "Lung adenocarcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_LUAD.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_LUAD.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_LUAD.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_LUAD.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_LUAD.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_LUAD.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_LUAD.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_LUAD.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("luad", info);

        info = new HashMap<>();
        info.put("disease", "Lung squamous cell carcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_LUSC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_LUSC.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_LUSC.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_LUSC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_LUSC.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_LUSC.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_LUSC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_LUSC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("lusc", info);

        info = new HashMap<>();
        info.put("disease", "Mesothelioma");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_MESO.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_MESO.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_MESO.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_MESO.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_MESO.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("meso", info);

        info = new HashMap<>();
        info.put("disease", "Ovarian serous cystadenocarcinoma");
        info.put("rnaseq_platform", "Illumina_HiSeq_2000");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_OV.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "bcgsc.ca_OV.IlluminaHiSeq_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "genome.wustl.edu_OV.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_OV.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_OV.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_OV.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_OV.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_OV.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("ov", info);

        info = new HashMap<>();
        info.put("disease", "Pancreatic adenocarcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_PAAD.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_PAAD.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_PAAD.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_PAAD.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_PAAD.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_PAAD.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("paad", info);

        info = new HashMap<>();
        info.put("disease", "Pheochromocytoma and Paraganglioma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_PCPG.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_PCPG.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_PCPG.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_PCPG.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_PCPG.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_PCPG.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("pcpg", info);

        info = new HashMap<>();
        info.put("disease", "Prostate adenocarcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_PRAD.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_PRAD.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_PRAD.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_PRAD.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_PRAD.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_PRAD.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("prad", info);

        info = new HashMap<>();
        info.put("disease", "Rectum adenocarcinoma");
        info.put("rnaseq_platform", "Illumina_GA2");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_READ.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_READ.IlluminaGA_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_READ.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_READ.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_READ.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_READ.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_READ.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_READ.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("read", info);

        info = new HashMap<>();
        info.put("disease", "Sarcoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_SARC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "ucsc.edu_SARC.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_SARC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_SARC.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_SARC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_SARC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("sarc", info);

        info = new HashMap<>();
        info.put("disease", "Skin Cutaneous Melanoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_SKCM.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_SKCM.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_SKCM.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_SKCM.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_SKCM.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_SKCM.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("skcm", info);

        info = new HashMap<>();
        info.put("disease", "Stomach adenocarcinoma");
        info.put("rnaseq_platform", "Illumina_GA2");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseq_data_dir_prefix", "bcgsc.ca_STAD.IlluminaGA_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_STAD.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_STAD.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_STAD.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_STAD.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_STAD.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_STAD.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("stad", info);

        info = new HashMap<>();
        info.put("disease", "Testicular Germ Cell Tumors");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_TGCT.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_TGCT.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_TGCT.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_TGCT.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_TGCT.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_TGCT.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("tgct", info);

        info = new HashMap<>();
        info.put("disease", "Thyroid carcinoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_THCA.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_THCA.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_THCA.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_THCA.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_THCA.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_THCA.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("thca", info);

        info = new HashMap<>();
        info.put("disease", "Thymoma");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_THYM.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_THYM.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_THYM.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_THYM.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_THYM.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("thym", info);

        info = new HashMap<>();
        info.put("disease", "Uterine Corpus Endometrial Carcinoma");
        info.put("rnaseq_platform", "Illumina_GA2");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("dnamethylation27_platform", "HumanMethylation27");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_UCEC.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("rnaseq_data_dir_prefix", "unc.edu_UCEC.IlluminaGA_RNASeq.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_UCEC.IlluminaGA_DNASeq.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_UCEC.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_UCEC.HumanMethylation450.Level_3");
        info.put("dnamethylation27_data_dir_prefix", "jhu-usc.edu_UCEC.HumanMethylation27.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_UCEC.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_UCEC.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("ucec", info);

        info = new HashMap<>();
        info.put("disease", "Uterine Carcinosarcoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_UCS.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "broad.mit.edu_UCS.IlluminaGA_DNASeq_curated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_UCS.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_UCS.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_UCS.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_UCS.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("ucs", info);

        info = new HashMap<>();
        info.put("disease", "Uveal Melanoma");
        info.put("dnaseq_platform", "Illumina_GA2");
        info.put("dnamethylation450_platform", "HumanMethylation450");
        info.put("rnaseqv2_platform", "Illumina_HiSeq_2000");
        info.put("mirnaseq_platform", "Illumina_HiSeq_2000");
        info.put("cnv_platform", "Genome_Wide_SNP_6");
        info.put("rnaseqv2_data_dir_prefix", "unc.edu_UVM.IlluminaHiSeq_RNASeqV2.Level_3");
	info.put("dnaseq_data_dir_prefix", "hgsc.bcm.edu_UVM.IlluminaGA_DNASeq_automated.Level_2");
	info.put("mirnaseq_data_dir_prefix", "bcgsc.ca_UVM.IlluminaHiSeq_miRNASeq.Level_3");
	info.put("dnamethylation450_data_dir_prefix", "jhu-usc.edu_UVM.HumanMethylation450.Level_3");
	info.put("cnv_data_dir_prefix", "broad.mit.edu_UVM.Genome_Wide_SNP_6.Level_3");
        info.put("cnv_magetab_dir_prefix", "broad.mit.edu_UVM.Genome_Wide_SNP_6.mage-tab");
        diseaseInfo.put("uvm", info);
    }

}
